name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: test
        run: go test -v ./...
      - name: install tailwind
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x86_64
          chmod +x tailwindcss-linux-x86_64
          mv tailwindcss-linux-x86_64 tailwindcss
      - name: build
        run: ./build.sh
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: orange
          path: ./orange

